#spring.application.name=JournalApp
#server.port=9090
#server.servlet.context-path=/journalApp
#
#
##spring.data.mongodb.host=localhost
##spring.data.mongodb.port=27017
#spring.data.mongodb.database=journalAppDB
#spring.data.mongodb.uri=mongodb+srv://nitish888kr_db_user:admin@cluster0.eo56jmi.mongodb.net/?appName=Cluster0
##spring.data.mongodb.host.username=journalAppDB
##spring.data.mongodb.host.password=journalAppDB
#spring.data.mongodb.auto-index-creation=true
#
##spring.security.user.name=user
##spring.security.user.password=password

